### ISSUE TITLE
MIT License?

### ISSUE THREAD

**Issue by znapfel** [hgezim/express-shopify-auth#1]
Hi Gezim,

First of all, thanks so much for creating this! 

As someone barely approaching competency with Shopify development, their authentication process and decision to use Koa over Express has been one of the most frustrating and challenging parts of learning the platform and getting even a simple Shopify app up and running. Especially when I've finally gotten comfortable with using Express.

I see that this says it's under an MIT license in the readme, but I don't see the actual license in the repo, so I wanted to confirm with you before I tried this out.

Also, are there any plans to keep this updated for when they roll out their [new session token based](https://docs.google.com/document/d/1KuWZc10Hnp0vCfR8ulYHVlazjA1RfXx9iDHb2d5e6Hk/edit) auth process over the summer? I'm excited to see what they come out with, but I'm worried it will also use Koa and probably either exclude (or create significant barriers for) a large portion of developers who want to try their hand at developing for the platform.

Thanks again!

**Comment by hgezim** [comment]
Hey @znapfel! Glad you found my port!

Yeah, it's MIT. I didn't think I'd need anything other than specifying that in the `package.json`. I guess a license file wouldn't hurt :)

If shopify ends up updating the koa package to add this new session token based auth then I plan to update this library as well. If it's a totally separate package that's a separate discussion. Remains to be seen.

**Comment by znapfel** [comment]
Sounds good! Thanks again for porting this!

**Comment by hgezim** [comment]
Happy to have someone care, @znapfel. Added license file here: 45bcb1066d9b43901af4b88c986c94d3f543d2ee
